apiVersion: batch/v1
kind: Job
metadata:
  name: test-klines-etl
  namespace: production
spec:
  template:
    spec:
      containers:
        - name: klines-etl
          image: registry.lan/klines-etl:latest
          volumeMounts:
            - name: db-creds
              mountPath: /app/keys
              readOnly: true
      volumes:
        - name: db-creds
          secret:
            secretName: db-creds
            items:
              - key: keys.env
                path: .env
      restartPolicy: Never
  backoffLimit: 0